---
# tasks file for Proxmox
- name: Create new vm snapshot
  community.general.proxmox_snap:
    api_user: root@pam
    api_password: XXX
    api_host: XXX.XXX.XXX.XXX
    vmid: "{{ item }}"
    state: present
    snapname: pre-updates
  loop:
    - 113
    - 106