---
# tasks file for Proxmox
- name: Create new vm snapshot
  community.general.proxmox_snap:
    api_user: root@pam
    api_password: 123456
    api_host: 192.168.178.200
    vmid: "{{ item }}"
    state: present
    snapname: pre-updates
  loop:
    - 113
    - 106