---
version: '2.1'

services:
  duplicati:
    image: ghcr.io/linuxserver/duplicati
    container_name: duplicati
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Berlin
    volumes:
      - /var/docker/duplicati/config:/config
      - /var/docker/duplicati/backups:/backups
      - /:/source
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.duplicati-secure.entrypoints=https"
      - "traefik.http.routers.duplicati-secure.rule=Host(`${DUPLICATI_URL}`)"
      - "traefik.http.routers.duplicati-secure.tls=true"
      - "traefik.http.routers.duplicati-secure.middlewares=secHeaders@file,duplicati-ipwhitelist"
      - "traefik.http.middlewares.duplicati-ipwhitelist.ipwhitelist.sourcerange=127.0.0.1/32, 192.168.178.0/24, 192.168.1.0/24"
      - "traefik.http.routers.duplicati-secure.service=duplicati"
      - "traefik.http.services.duplicati.loadbalancer.server.port=8200"
      - "traefik.docker.network=proxy"    
    restart: unless-stopped

networks:
  proxy:
    external:
      name: proxy